
####this test file was generated by GEMINI
####PROMPT: create a simple client that tests my serevr


import socket
import struct

def send_test_query(ip="127.0.0.1", port=53):
    # 1. Create a UDP socket
    sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
    sock.settimeout(2) # Don't wait forever if the server fails

    # 2. Build a dummy DNS Header (12 bytes)
    # ID: 0x1234, Flags: 0x0100 (Standard query), Questions: 1, 
    # Answer RRs: 0, Authority RRs: 0, Additional RRs: 0
    header = struct.pack('!HHHHHH', 0x1234, 0x0100, 1, 0, 0, 0)
    
    # 3. Basic Query for "example.com" (simplified for testing)
    # Normally this involves specific encoding, but for a "ping" test, 
    # we just want to see if the server receives the packet.
    query = b'\x07example\x03com\x00\x00\x01\x00\x01'
    packet = header + query

    try:
        print(f"Sending test packet to {ip}:{port}...")
        sock.sendto(packet, (ip, port))

        # 4. Wait for response
        data, addr = sock.recvfrom(1024)
        print(f"Success! Received {len(data)} bytes back from {addr}")
        print(f"Raw hex response: {data.hex()}")

    except socket.timeout:
        print("Error: Request timed out. Is the server running?")
    except Exception as e:
        print(f"An error occurred: {e}")
    finally:
        sock.close()

if __name__ == "__main__":
    send_test_query()